version: '3.8'

services:
  tsx-trend-api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/map/geojson"]
      interval: 30s
      timeout: 10s
      retries: 3


